version: '2'
services:
  web:
    build: .
    env_file:
      - secret.env
    depends_on:
      - db
    ports:
     - "4000:4000"
    volumes:
     - .:/app
  db:
    image: postgres:9.5.4
    ports:
      - "5432"